// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 提供 USB 设备发现能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListDevices 枚举所有 DJI 百望 4G 模组(VID 2C7C),返回描述符信息。
 * 不长期持有设备句柄 — 每次调用独立开闭,供前端刷新设备列表。
 */
export function ListDevices(): $CancellablePromise<$models.USBDeviceInfo[] | null> {
    return $Call.ByID(1184853013);
}

/**
 * ReportDOM 接收前端上报的 DOM 快照(开发期调试自动化:写 /tmp 供外部检查)。
 * 前端定期调用此方法,把真实 webview 的 DOM(含 wails runtime 渲染结果)写到文件。
 */
export function ReportDOM(dom: string): $CancellablePromise<void> {
    return $Call.ByID(566462400, dom);
}
