// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 提供 USB 设备发现 + 手动启用(打开 AT 通道)能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect 手动启用设备:打开 MI_02 AT 通道并初始化 modem(AT→ATE0→CMEE→CPIN→CMGF→CNMI→CPMS)。
 * 启用后设备进入可用状态,后续可做 AT 命令/短信/设备信息查询。
 * 重复启用返回错误(需先 Disconnect)。
 */
export function Connect(): $CancellablePromise<void> {
    return $Call.ByID(1134389156);
}

/**
 * Disconnect 断开设备(关闭 modem,内部释放 AT transport)。
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1488517080);
}

/**
 * GetDeviceInfo 查询已启用设备的详细信息(IMEI/ICCID/IMSI/运营商/本机号/固件/信号 dBm)。
 * 需先 Connect;每字段一条 AT 命令,整体约 3-5 秒。
 */
export function GetDeviceInfo(): $CancellablePromise<$models.DeviceInfo | null> {
    return $Call.ByID(1966400872).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsConnected 返回设备是否已启用(AT 通道是否打开)。
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(2524771033);
}

/**
 * ListDevices 枚举所有 DJI 百望 4G 模组(VID 2C7C),返回描述符信息。
 * 不长期持有设备句柄 — 每次调用独立开闭,供前端刷新设备列表。
 */
export function ListDevices(): $CancellablePromise<$models.USBDeviceInfo[]> {
    return $Call.ByID(1184853013).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ReportDOM 接收前端上报的 DOM 快照(开发期调试自动化:写 /tmp 供外部检查)。
 */
export function ReportDOM(dom: string): $CancellablePromise<void> {
    return $Call.ByID(566462400, dom);
}

// Private type creation functions
const $$createType0 = $models.DeviceInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.USBDeviceInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
