// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialerService 管理 QMI 拨号 + SOCKS5 代理的完整生命周期。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dial 执行 QMI 拨号:Open MI_04 → SYNC → StartCore → Connect(WDS StartNetwork)。
 * 拿到运营商 IP/DNS/MTU。apn 为空时默认 3gnet。
 */
export function Dial(apn: string): $CancellablePromise<void> {
    return $Call.ByID(2345156911, apn);
}

/**
 * GetConnection 返回拨号后的网络配置(IP/Gateway/DNS/MTU/IPv6)。
 */
export function GetConnection(): $CancellablePromise<$models.ConnectionInfo | null> {
    return $Call.ByID(315581859).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStats 返回 relay 流量统计。
 */
export function GetStats(): $CancellablePromise<$models.RelayStats | null> {
    return $Call.ByID(4058530830).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Hangup 断开拨号(含 SOCKS5 自动停止)+ 释放 transport/client/manager。
 */
export function Hangup(): $CancellablePromise<void> {
    return $Call.ByID(3676562832);
}

/**
 * IsConnected 返回是否已拨号。
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(743267596);
}

/**
 * IsSOCKS5Running 返回 SOCKS5 是否在运行。
 */
export function IsSOCKS5Running(): $CancellablePromise<boolean> {
    return $Call.ByID(3756838760);
}

/**
 * IsTUNRunning 返回 TUN helper 是否在运行。
 */
export function IsTUNRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1265052303);
}

/**
 * StartSOCKS5 启动 SOCKS5 代理(netstack,无需 admin)。需先 Dial。
 */
export function StartSOCKS5(addr: string): $CancellablePromise<void> {
    return $Call.ByID(3637284927, addr);
}

/**
 * StartTUN 启动 TUN 模式:先 build tun-helper binary,再 osascript sudo 启动(弹密码框)。
 * tun-helper 以 root 独立进程运行(创建 utun + 拨号 + relay + DNS),app 监控其 PID。
 */
export function StartTUN(apn: string): $CancellablePromise<void> {
    return $Call.ByID(233528346, apn);
}

/**
 * StopSOCKS5 停止 SOCKS5 代理(保持拨号)。
 */
export function StopSOCKS5(): $CancellablePromise<void> {
    return $Call.ByID(849760785);
}

/**
 * StopTUN 停止 TUN(osascript sudo kill root 进程)。
 */
export function StopTUN(): $CancellablePromise<void> {
    return $Call.ByID(2236449728);
}

// Private type creation functions
const $$createType0 = $models.ConnectionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.RelayStats.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
