// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * USBDeviceInfo 描述一个发现的 USB 设备,序列化后传给前端。
 */
export interface USBDeviceInfo {
    /**
     * "2c7c"
     */
    "vid": string;

    /**
     * "0125"
     */
    "pid": string;

    /**
     * iProduct 字符串
     */
    "product": string;

    /**
     * iManufacturer 字符串
     */
    "vendor": string;

    /**
     * iSerial 字符串
     */
    "serial": string;

    /**
     * 接口数(EC25 模式通常 5)
     */
    "interfaces": number;
}
