// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionInfo 是拨号后的网络配置(前端展示用)。
 */
export class ConnectionInfo {
    "ipv4Address": string;
    "gateway": string;
    "dns1": string;
    "dns2": string;
    "mtu": number;
    "ipv6Address": string;

    /** Creates a new ConnectionInfo instance. */
    constructor($$source: Partial<ConnectionInfo> = {}) {
        if (!("ipv4Address" in $$source)) {
            this["ipv4Address"] = "";
        }
        if (!("gateway" in $$source)) {
            this["gateway"] = "";
        }
        if (!("dns1" in $$source)) {
            this["dns1"] = "";
        }
        if (!("dns2" in $$source)) {
            this["dns2"] = "";
        }
        if (!("mtu" in $$source)) {
            this["mtu"] = 0;
        }
        if (!("ipv6Address" in $$source)) {
            this["ipv6Address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo($$parsedSource as Partial<ConnectionInfo>);
    }
}

/**
 * DeviceInfo 是启用后可查询的设备详细信息(每字段对应一条 AT 命令)。
 */
export class DeviceInfo {
    "imei": string;
    "iccid": string;
    "imsi": string;
    "carrier": string;
    "phone": string;
    "firmware": string;
    "signalDbm": number;
    "signalOk": boolean;

    /** Creates a new DeviceInfo instance. */
    constructor($$source: Partial<DeviceInfo> = {}) {
        if (!("imei" in $$source)) {
            this["imei"] = "";
        }
        if (!("iccid" in $$source)) {
            this["iccid"] = "";
        }
        if (!("imsi" in $$source)) {
            this["imsi"] = "";
        }
        if (!("carrier" in $$source)) {
            this["carrier"] = "";
        }
        if (!("phone" in $$source)) {
            this["phone"] = "";
        }
        if (!("firmware" in $$source)) {
            this["firmware"] = "";
        }
        if (!("signalDbm" in $$source)) {
            this["signalDbm"] = 0;
        }
        if (!("signalOk" in $$source)) {
            this["signalOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo($$parsedSource as Partial<DeviceInfo>);
    }
}

/**
 * RelayStats 是 SOCKS5 relay 的流量统计。
 */
export class RelayStats {
    "txPackets": number;
    "txBytes": number;
    "rxPackets": number;
    "rxBytes": number;

    /** Creates a new RelayStats instance. */
    constructor($$source: Partial<RelayStats> = {}) {
        if (!("txPackets" in $$source)) {
            this["txPackets"] = 0;
        }
        if (!("txBytes" in $$source)) {
            this["txBytes"] = 0;
        }
        if (!("rxPackets" in $$source)) {
            this["rxPackets"] = 0;
        }
        if (!("rxBytes" in $$source)) {
            this["rxBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayStats instance from a string or object.
     */
    static createFrom($$source: any = {}): RelayStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayStats($$parsedSource as Partial<RelayStats>);
    }
}

/**
 * SMS 是一条解码后的短信(前端展示用)。
 */
export class SMS {
    /**
     * SIM 存储索引(AT+CMGD 用)
     */
    "index": number;

    /**
     * 发件人 MSISDN
     */
    "sender": string;

    /**
     * 正文(UCS-2/GSM7 自动解码)
     */
    "body": string;

    /**
     * 服务中心时间戳
     */
    "timestamp": string;

    /** Creates a new SMS instance. */
    constructor($$source: Partial<SMS> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("sender" in $$source)) {
            this["sender"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMS instance from a string or object.
     */
    static createFrom($$source: any = {}): SMS {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SMS($$parsedSource as Partial<SMS>);
    }
}

/**
 * USBDeviceInfo 描述一个发现的 USB 设备,序列化后传给前端。
 */
export class USBDeviceInfo {
    /**
     * "2c7c"
     */
    "vid": string;

    /**
     * "0125"
     */
    "pid": string;

    /**
     * iProduct 字符串
     */
    "product": string;

    /**
     * iManufacturer 字符串
     */
    "vendor": string;

    /**
     * iSerial 字符串
     */
    "serial": string;

    /**
     * 接口数(EC25 模式通常 5)
     */
    "interfaces": number;

    /** Creates a new USBDeviceInfo instance. */
    constructor($$source: Partial<USBDeviceInfo> = {}) {
        if (!("vid" in $$source)) {
            this["vid"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = "";
        }
        if (!("product" in $$source)) {
            this["product"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("interfaces" in $$source)) {
            this["interfaces"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new USBDeviceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): USBDeviceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new USBDeviceInfo($$parsedSource as Partial<USBDeviceInfo>);
    }
}
