// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionInfo 是拨号后的网络配置(前端展示用)。
 */
export interface ConnectionInfo {
    "ipv4Address": string;
    "gateway": string;
    "dns1": string;
    "dns2": string;
    "mtu": number;
    "ipv6Address": string;
}

/**
 * DeviceInfo 是启用后可查询的设备详细信息(每字段对应一条 AT 命令)。
 */
export interface DeviceInfo {
    "imei": string;
    "iccid": string;
    "imsi": string;
    "carrier": string;
    "phone": string;
    "firmware": string;
    "signalDbm": number;
    "signalOk": boolean;
}

/**
 * RelayStats 是 SOCKS5 relay 的流量统计。
 */
export interface RelayStats {
    "txPackets": number;
    "txBytes": number;
    "rxPackets": number;
    "rxBytes": number;
}

/**
 * SMS 是一条解码后的短信(前端展示用)。
 */
export interface SMS {
    /**
     * SIM 存储索引(AT+CMGD 用)
     */
    "index": number;

    /**
     * 发件人 MSISDN
     */
    "sender": string;

    /**
     * 正文(UCS-2/GSM7 自动解码)
     */
    "body": string;

    /**
     * 服务中心时间戳
     */
    "timestamp": string;
}

/**
 * USBDeviceInfo 描述一个发现的 USB 设备,序列化后传给前端。
 */
export interface USBDeviceInfo {
    /**
     * "2c7c"
     */
    "vid": string;

    /**
     * "0125"
     */
    "pid": string;

    /**
     * iProduct 字符串
     */
    "product": string;

    /**
     * iManufacturer 字符串
     */
    "vendor": string;

    /**
     * iSerial 字符串
     */
    "serial": string;

    /**
     * 接口数(EC25 模式通常 5)
     */
    "interfaces": number;
}
