// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SMSService 复用 DeviceService.modem(同包可直接访问私有字段)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSMS 删除 SIM 上指定索引的短信(AT+CMGD)。
 */
export function DeleteSMS(index: number): $CancellablePromise<void> {
    return $Call.ByID(3658553713, index);
}

/**
 * ListSMS 读取 SIM 已存短信并解码(AT+CMGL=4 → DecodeDeliver,UCS-2/GSM7 自动)。
 */
export function ListSMS(): $CancellablePromise<$models.SMS[]> {
    return $Call.ByID(3546783768).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SendSMS 发送短信(长短信自动分段,内部 CMGS 两步握手)。
 */
export function SendSMS(recipient: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(1292919526, recipient, body);
}

// Private type creation functions
const $$createType0 = $models.SMS.createFrom;
const $$createType1 = $Create.Array($$createType0);
